version: '3'

volumes:
  backend:
    driver: local
    driver_opts:
      type: none
      device: ./backend/app
      o: bind
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ./frontend/front
      o: bind
  img:
    driver: local
    driver_opts:
      type: none
      device: ./backend/media/uploads
      o: bind
networks:
  network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    restart: always
    networks:
      - network

  database:
    container_name: database
    image: postgres:latest
    restart: always
    ports:
      - 5435:5435
    networks:
      - network
    env_file:
      - .env

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - backend:/app
    ports:
      - 8000:8000
    networks:
      - network
    restart: always
    depends_on:
      - database
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/usr/src/app
    ports:
     - 423:423
    restart: always
    networks:
      - network
