version: '3'

networks:
  network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    restart: always
    networks:
      - network

  backend:
    container_name: backend
    build: ./backend
    networks:
      - network
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - 423:423
    restart: always
    networks:
      - network
