version: "1.29.2"

volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      device: /home/eryilmaz/data/backend
      o: bind
  frontend-data:
    driver: local
    driver_opts:
      type: none
      device: /home/eryilmaz/data/frontend
      o: bind
  database-data:
    driver: local
    driver_opts:
      type: none
      device: /home/eryilmaz/data/frontend
      o: bind
networks:
  network:
    driver: bridge

services:
  backend:

  frontend:

  database:

  nginx: